### ISSUE TITLE
Crash your opponent

### ISSUE THREAD

**Issue by SamuelSchwegler** [scg-unibe-ch/ese2017-team9#2]
Hallo Zusammen, wir hatten Probleme beim Starten eures Projektes. Dank einer kurzen Erklärung am letzten Mittwoch hat es dann aber geklapt.

Hier unsere gefundenen Bugs:
<ol>
<li>Die Eingaben bei den Inputfeldern sind nicht auf den Datentypen ausgerichtet. Man kann statt Zahlen auch Text eingeben oder Mailadressen die keine sind</li>
<li>Es gibt keine Felder die Required sind (Ausfüllen zwingend). Leere Felder werden "null" gesetzt.</li>
<li>Wenn in einem Inputfeld type Text eine Eingabe von mehr als 256 Zeichen länge gemacht wird kann sie nicht aufgenommen werden.</li>
<li>Wenn ich den Namen eines existierenden Users auf eine Länge von über 256 Zeichen verlängern will akzeptiert das Programm die Änderung nicht und git folgenden Fehler aus: "The username is allready taken", dass passiert weil auch hier die eingabe nicht akzeptiert wird und der bisherige Name weitergeleitet wird.</li>
<li>Beim Login wird nicht auf Gross und Kleinschreibung beim Username geachtet. Beim Passwort aber schon.</li>
<li> Ich kann mich gleichzeitig als Driver und Admin registrieren. (Kann natürlich auch gewollt sein)</li>
<li> Wenn ich mich als Driver einlogge kann ich mir meine Tours anzeigen lassen, das läuft über den Username in der URL: http://localhost:8080/driverTours?loggedInUser=Samuel, nun kann ich via dieser URL bei allen anderen Drivers die Tours anschauen in dem ich loggedInUser=AndererName setze. Das funktioniert aber nur wenn ein Driver eingeloggt ist. Als Admin bekomme ich den Hinnweis: "You have no access rights to this site." Ausser ich bin gleichzeitig Admin und Driver.</li>
<li> Es ist nicht möglich eine Delivery zu erstellen: 
"There was an unexpected error (type=Bad Request, status=400).
Validation failed for object='delivery'. Error count: 2", erscheint beim Absenden.</li>
<li>Bei Delivery.java wird mit deliveryId Datentyp Long gearbeitet, der Customer ist aber Typ long. Bei Customer.java ist die customerId wieder Typ Long. Das gleiche gilt auch für Tour.java</li>
</ol>

Noch etwas bezüglich Usability: Wir konnten nicht auf Anhieb erkennen, welches Element als Link gedacht ist, es ist ein weisser Link auf Türkis-farbenen Hintergrund.

Wir haben euer Programm mit InteliJ Ultimate Edition und auf Firefox Version 56.0 auf Ubuntu getestet.

Danke für die Geduld und weiterhin frohes schaffen
ese2017-team8

**Comment by manuelamateo** [comment]
Fixed except:
5. No actions needed
6. No actions needed
7.  create new issue
