### ISSUE TITLE
Filter Items

### ISSUE THREAD

**Issue by manuelamateo** [scg-unibe-ch/ese2017-team9#7]
Description: The admin can filter every item type by criterions. Default is no criterion. The list is always sort by alphabet.
TODO:
- User: locked, Admin, Driver
- Delivery: Status (Open, Scheduled, ...)
- Tour: Driver (dynamic list)

**Comment by manuelamateo** [comment]
SY: Delivery und Tour
ME: User

**Comment by manuelamateo** [comment]
User filter works
Strange URL: http://localhost:8080/user?filter=admins&_csrf=34de211d-d353-47c9-a2d9-48675e513161

**Comment by Christofsy** [comment]
Delivery filter works

**Comment by manuelamateo** [comment]
Tour filter works
